# 用于保持与英文的行数对齐，请勿移除
# 用于保持与英文的行数对齐，请勿移除
# 用于保持与英文的行数对齐，请勿移除
class LocalizerZH:
    # 保留
    switch_language: str = (
        "请选择应用语言，新的语言设置将在下次启动时生效 …"
        "\n"
        "Select application language, changes will take effect on restart …"
    )
    switch_language_toast: str = (
        "应用语言切换成功，请重启应用生效 …"
        "\n"
        "Language switched successfully, please restart the application for changes to take effect …"
    )

    # 通用
    add: str = "新增"
    edit: str = "修改"
    delete: str = "删除"
    rename: str = "重命名"
    select_file: str = "选择文件"
    select_folder: str = "选择文件夹"
    supported_files: str = "支持的文件"
    back: str = "返回"
    stop: str = "停止"
    start: str = "开始"
    save: str = "保存"
    timer: str = "定时器"
    reset: str = "重置"
    basic_settings: str = "基础设置"
    api_url: str = "接口地址"
    table_col_source: str = "原文"
    table_col_translation: str = "译文"
    table_col_replacement: str = "替换"
    table_col_rule: str = "规则"
    status: str = "当前状态："
    status_enabled: str = "当前状态：已启用"
    status_disabled: str = "当前状态：未启用"
    issue_kana_residue: str = "假名残留"
    issue_hangeul_residue: str = "谚文残留"
    close: str = "关闭"
    alert: str = "提醒"
    warning: str = "警告"
    confirm: str = "确认"
    cancel: str = "取消"
    auto: str = "自动"
    wiki: str = "功能说明"
    view_more_info: str = "查看更多信息"
    filter: str = "过滤"
    search: str = "搜索"
    placeholder: str = "请输入关键词 …"
    task_failed: str = "任务执行失败 …"
    task_success: str = "任务执行成功 …"
    task_running: str = "任务正在执行中 …"
    task_batch_translation_progress: str = "正在翻译，第 {CURRENT} 项，共 {TOTAL} 项 …"
    task_batch_translation_success: str = "翻译完成，成功 {SUCCESS} 条，失败 {FAILED} 条 …"
    toast_save: str = "已保存 …"
    toast_reset: str = "已重置 …"
    toast_processing: str = "处理中 …"
    move_up: str = "上移"
    move_down: str = "下移"
    move_top: str = "置顶"
    move_bottom: str = "置底"
    export_translation: str = "生成译文"
    export_translation_confirm: str = "确定要生成译文文件吗 …?"
    export_translation_start: str = "生成译文中 …"
    export_translation_done: str = "译文已保存至 [blue]{PATH}[/blue] …"
    export_translation_success: str = "译文生成完成 …"
    export_translation_failed: str = "译文生成失败 …"
    alert_no_data: str = "没有有效数据 …"
    alert_project_not_loaded: str = "请先加载工程文件 …"
    alert_no_active_model: str = "未找到激活的模型配置 …"
    alert_confirm_reset_data: str = "是否确认重置数据 …?"
    alert_confirm_delete_data: str = "是否确认删除数据 …?"
    alert_reset_timer: str = "将重置定时器，是否确认 …?"
    alert_file_already_exists: str = "文件已存在 …"
    alert_preset_already_exists: str = "预设已存在，是否确认覆盖 …?"
    search_prev_btn: str = "上一个"
    search_next_btn: str = "下一个"
    search_prev_match: str = "上一个匹配项"
    search_next_match: str = "下一个匹配项"
    search_regex_on: str = (
        "正则模式"
        "\n"
        "当前状态：已启用"
    )
    search_regex_off: str = (
        "正则模式"
        "\n"
        "当前状态：未启用"
    )
    search_regex_invalid: str = "正则表达式无效"
    search_no_match: str = "未找到匹配项"
    search_regex_btn: str = "正则"
    search_match_info: str = "第 {current} 项，共 {total} 项"
    search_no_result: str = "无结果"
    shortcut_ctrl_s: str = "Ctrl+S"

    # 主页面
    app_close_message_box: str = "确定是否退出程序 …?"
    app_exit_countdown: str = "退出中 … {SECONDS} …"
    app_new_version: str = "点击下载更新版本！"
    app_new_version_toast: str = "已找到新版本，版本号为 {VERSION}，请点击左下角按钮下载更新 …"
    app_new_version_update: str = "正在下载 {PERCENT} …"
    app_new_version_failure: str = "新版本下载失败 … "
    app_new_version_success: str = "新版本下载成功 … "
    app_new_version_downloaded: str = "点击应用新版本！"
    app_new_version_applying: str = "正在应用更新 …"
    app_new_version_apply_failed: str = "更新失败，已回滚 …"
    app_new_version_waiting_restart: str = "更新完成，应用即将关闭 …"
    app_project_closed_toast: str = "当前项目已关闭 …"
    app_close_project_btn: str = "关闭项目"
    app_theme_btn: str = "变换自如"
    app_language_btn: str = "字字珠玑"
    app_settings_page: str = "应用设置"
    app_model_page: str = "模型管理"
    app_translation_page: str = "翻译"
    app_analysis_page: str = "分析"
    app_proofreading_page: str = "校对"
    app_workbench_page: str = "工作台"
    app_expert_settings_page: str = "专家设置"
    app_glossary_page: str = "术语表"
    app_text_preserve_page: str = "文本保护"
    app_text_replacement_page: str = "文本替换"
    app_pre_translation_replacement_page: str = "译前替换"
    app_post_translation_replacement_page: str = "译后替换"
    app_custom_prompt_navigation_item: str = "自定义提示词"
    app_analysis_prompt_page: str = "分析提示词"
    app_translation_prompt_page: str = "翻译提示词"
    app_laboratory_page: str = "实验室"
    app_treasure_chest_page: str = "百宝箱"

    # 路径
    path_translated: str = "译文"
    path_translated_bilingual: str = "译文_双语对照"

    # 日志
    log_crash: str = "出现严重错误，应用即将退出，错误信息已保存至日志文件 …"
    log_proxy: str = "网络代理已启用 …"
    log_expert_mode: str = "专家模式已启用 …"
    log_api_test_fail: str = (
        "接口测试失败 …"
        "\n"
        "原因：{REASON}"
    )
    log_read_file_fail: str = "文件读取失败 …"
    log_write_file_fail: str = "文件写入失败 …"
    log_unknown_reason: str = "未知原因"
    log_cli_verify_language: str = "参数发生错误：无效的语言 …"
    log_cli_target_language_all_unsupported: str = "译文语言不支持 ALL …"
    log_cli_quality_rule_file_not_found: str = (
        "参数发生错误：规则文件不存在 …"
        "\n"
        "参数：{ARG}"
        "\n"
        "路径：{PATH}"
    )
    log_cli_quality_rule_file_unsupported: str = (
        "参数发生错误：规则文件格式不受支持（仅支持 .json/.xlsx） …"
        "\n"
        "参数：{ARG}"
        "\n"
        "路径：{PATH}"
    )
    log_cli_quality_rule_import_failed: str = (
        "质量规则导入失败 …"
        "\n"
        "参数：{ARG}"
        "\n"
        "路径：{PATH}"
        "\n"
        "原因：{REASON}"
    )
    log_cli_text_preserve_mode_invalid: str = (
        "参数发生错误：文本保护参数组合无效 …"
        "\n"
        "--text_preserve_mode: {MODE}"
        "\n"
        "--text_preserve: {PATH}"
        "\n"
        "说明：mode=custom 时必须提供 --text_preserve；提供 --text_preserve 时 mode 必须为 custom"
    )

    # 引擎
    engine_no_items: str = "没有找到需要处理数据，请确认 …"
    engine_task_done: str = "任务已完成 …"
    engine_task_fail: str = "任务未能全部完成，仍有部分数据未处理，请检查处理结果 …"
    engine_task_stop: str = "任务已停止 …"
    engine_task_rule_filter: str = "规则过滤已完成，共过滤 {COUNT} 个无需翻译的条目 …"
    engine_task_language_filter: str = "语言过滤已完成，共过滤 {COUNT} 个非目标原文语言条目 …"
    engine_task_scheduler_stop_with_untranslated: str = "任务调度器停止，但仍有 {COUNT} 个未翻译条目（可能因异常丢失）"
    translator_task_status_info: str = "拆分次数：{SPLIT} | 单条重试次数：{RETRY} | 任务长度阈值：{THRESHOLD}"
    translator_task_force_accept_info: str = " | 已强制放行：{REASON}"
    translator_simple_log_prefix: str = "简略日志"
    engine_api_name: str = "接口名称"
    engine_api_model: str = "接口模型"
    engine_response_think: str = "模型思考内容："
    engine_response_result: str = "模型回复内容："
    engine_task_success: str = "任务耗时 {TIME} 秒，文本行数 {LINES} 行，输入消耗 {PT} Tokens，输出消耗 {CT} Tokens"
    api_tester_key: str = "正在测试密钥："
    api_tester_messages: str = "任务提示词："
    api_tester_timeout: str = "请求超时（{SECONDS} 秒）"
    api_tester_result: str = "共测试 {COUNT} 个接口，成功 {SUCCESS} 个，失败 {FAILURE} 个 …"
    api_tester_result_failure: str = "失败的密钥："
    api_tester_token_info: str = "Token 使用：输入 {INPUT}，输出 {OUTPUT}，耗时 {TIME} 秒"
    translator_mtool_optimizer_pre_log: str = "MToolOptimizer 预处理已完成，共过滤 {COUNT} 个包含重复子句的条目 …"
    translator_mtool_optimizer_post_log: str = "MToolOptimizer 后处理已完成 …"
    translator_response_check_fail: str = "返回数据错误，将自动重试，原因：{REASON}"
    translator_response_check_fail_all: str = "全部译文质量校验失败，将自动切分重试，原因：{REASON}"
    translator_response_check_fail_part: str = "部分译文质量校验失败，将自动切分重试，原因：{REASON}"
    translator_response_check_fail_force: str = "译文校验未通过"
    response_checker_fail_data: str = "数据结构错误"
    response_checker_fail_timeout: str = "网络请求超时"
    response_checker_fail_line_count: str = "行数不一致"
    response_checker_fail_degradation: str = "发生退化现象"
    response_checker_line_error_empty_line: str = "存在空行"
    response_checker_line_error_similarity: str = "较高相似度"
    project_store_ingesting_assets: str = "正在收纳资产 …"
    project_store_ingesting_file: str = "正在收纳资产：{NAME}"
    project_store_parsing_items: str = "正在解析翻译条目 …"
    project_store_created: str = "工程创建完成 …"
    project_store_file_not_found: str = "工程文件不存在: {PATH}"

    # 应用设置
    app_settings_page_expert_title: str = "专家模式"
    app_settings_page_expert_content: str = "启用此功能后，将显示更多日志信息并提供更多高级设置选项（将在应用重启后生效）"
    app_settings_page_scale_factor_title: str = "全局缩放比例"
    app_settings_page_scale_factor_content: str = "启用此功能后，应用界面将按照所选比例进行缩放（将在应用重启后生效）"
    app_settings_page_proxy_url: str = "示例 - http://127.0.0.1:7890"
    app_settings_page_proxy_url_title: str = "网络代理"
    app_settings_page_proxy_url_content: str = "启用此功能后，将使用设置的代理地址发送网络请求（将在应用重启后生效）"
    app_settings_page_close: str = "应用即将关闭，请确认 …"

    # 模型管理
    model_page_activate: str = "激活模型"
    model_page_task_setting: str = "任务设置"
    model_page_advanced_setting: str = "高级设置"
    model_page_test: str = "测试模型"
    model_page_adjust_order: str = "调整排序"
    model_page_delete: str = "删除模型"
    model_page_reset: str = "重置模型"
    model_page_category_preset_title: str = "预设模型"
    model_page_category_preset_desc: str = "应用内置的预设模型"
    model_page_category_google_title: str = "自定义 Google 模型"
    model_page_category_google_desc: str = "兼容 Google Gemini API 格式的自定义模型"
    model_page_category_openai_title: str = "自定义 OpenAI 模型"
    model_page_category_openai_desc: str = "兼容 OpenAI API 格式的自定义模型"
    model_page_category_anthropic_title: str = "自定义 Anthropic 模型"
    model_page_category_anthropic_desc: str = "兼容 Anthropic Claude API 格式的自定义模型"
    model_page_migrated_toast: str = "检测到 {COUNT} 个预设模型已失效，已自动迁移至自定义模型分类 …"
    model_page_delete_last_one_toast: str = "每个分类至少需要保留一个模型，无法删除 …"
    model_page_reset_success_toast: str = "模型已重置 …"
    model_basic_setting_page_name: str = "请输入模型名称 …"
    model_basic_setting_page_name_title: str = "模型名称"
    model_basic_setting_page_name_content: str = "请输入模型名称，仅用于应用内显示，无实际作用"
    model_basic_setting_page_api_url: str = "请输入接口地址 …"
    model_basic_setting_page_api_url_content: str = "请输入接口地址，请注意辨别结尾是否需要添加 /v1"
    model_basic_setting_page_api_key: str = "请输入接口密钥 …"
    model_basic_setting_page_api_key_title: str = "接口密钥"
    model_basic_setting_page_api_key_content: str = "请输入接口密钥，例如 sk-d0daba12345678fd8eb7b8d31c123456，填入多个密钥可以轮询使用，每行一个"
    model_basic_setting_page_model_id: str = "请输入模型标识 …"
    model_basic_setting_page_model_id_title: str = "模型标识"
    model_basic_setting_page_model_id_content: str = "当前使用的模型标识为 {MODEL}"
    model_basic_setting_page_model_id_edit: str = "手动输入"
    model_basic_setting_page_model_id_sync: str = "在线获取"
    model_basic_setting_page_model_id_input: str = "输入"
    model_basic_setting_page_model_id_fetch: str = "获取"
    model_basic_setting_page_model_id_test: str = "测试"
    model_basic_setting_page_thinking_title: str = "思考等级"
    model_basic_setting_page_thinking_content: str = "设置模型的思考行为，会影响思考的时间和消耗，点击问号图标查看支持的模型列表"
    model_basic_setting_page_thinking_off: str = "无"
    model_basic_setting_page_thinking_low: str = "低"
    model_basic_setting_page_thinking_medium: str = "中"
    model_basic_setting_page_thinking_high: str = "高"
    model_basic_setting_page_input_token_title: str = "输入 Token 限制"
    model_basic_setting_page_input_token_content: str = "每个任务输入文本的最大 Token 数量"
    model_basic_setting_page_output_token_title: str = "输出 Token 限制"
    model_basic_setting_page_output_token_content: str = "每个任务输出文本的最大 Token 数量，0 = 自动"

    model_basic_setting_page_rpm_title: str = "每分钟请求数限制 (RPM)"
    model_basic_setting_page_rpm_content: str = (
        "每分钟执行的任务总数量的最大值，即 <font color='darkgoldenrod'><b>RPM</b></font> 限制"
        "<br>"
        "部分平台会对网络请求的速率进行限制，请参考 API 平台的文档进行设置，0 = 无限制"
        ""
        ""
    )
    model_basic_setting_page_concurrency_title: str = "并发任务数限制"
    model_basic_setting_page_concurrency_content: str = (
        "同时执行的任务数量的最大值"
        "<br>"
        "合理设置可以显著加快任务的完成速度，请参考 API 平台的文档进行设置，0 = 自动"
        ""
        ""
    )
    model_advanced_setting_page_headers_title: str = "自定义请求头"
    model_advanced_setting_page_headers_content: str = "自定义请求头参数，请谨慎设置，错误的值可能导致结果异常或者请求报错"
    model_advanced_setting_page_headers_placeholder: str = '例如：{"Authorization": "Bearer xxx"}'
    model_advanced_setting_page_body_title: str = "自定义请求体"
    model_advanced_setting_page_body_content: str = "自定义请求体参数，请谨慎设置，错误的值可能导致结果异常或者请求报错"
    model_advanced_setting_page_body_placeholder: str = '例如：{"seed": 42}'
    model_advanced_setting_page_param_caution: str = "请谨慎设置，错误的值可能导致结果异常或者请求报错"
    model_advanced_setting_page_top_p_title: str = "top_p"
    model_advanced_setting_page_temperature_title: str = "temperature"
    model_advanced_setting_page_presence_penalty_title: str = "presence_penalty"
    model_advanced_setting_page_frequency_penalty_title: str = "frequency_penalty"
    model_advanced_setting_page_json_format_error: str = "JSON 格式错误，请输入有效的 JSON 对象"
    model_selector_page_title: str = "可用的模型列表"
    model_selector_page_content: str = "点击选择要使用的模型"
    model_selector_page_fail: str = "获取模型列表失败，请检查接口配置 …"
    model_selector_page_loading: str = "正在获取模型列表 …"

    # 工程页
    project_new_project_title: str = "新建工程"
    project_new_project_subtitle: str = "选择源文件创建 .lg 工程文件，创建完成后即不再需要源文件。"
    project_new_project_btn: str = "创建工程"
    project_open_project_title: str = "打开工程"
    project_open_project_subtitle: str = "加载现有的 .lg 工程文件以继承翻译进度、翻译规则继续工作。"
    project_recent_projects_title: str = "最近打开"
    project_drop_zone_source_title: str = "点击或拖拽源文件"
    project_drop_zone_lg_title: str = "点击或拖拽 .lg 文件"
    project_fmt_title: str = "支持文件格式"
    project_fmt_subtitle: str = "字幕"
    project_fmt_ebook: str = "电子书"
    project_fmt_markdown: str = "Markdown"
    project_fmt_renpy: str = "RenPy 导出游戏文本"
    project_fmt_mtool: str = "MTool 导出游戏文本"
    project_fmt_sextractor: str = "SExtractor 导出游戏文本"
    project_fmt_vntextpatch: str = "VNTextPatch 导出游戏文本"
    project_fmt_trans_proj: str = "Translator++ 项目文件"
    project_fmt_trans_export: str = "Translator++ 导出游戏文本"
    project_fmt_wolf: str = "WOLF 官方翻译工具游戏文本"
    project_select_source_dir_title: str = "选择源文件目录"
    project_toast_no_valid_file: str = "该目录下没有支持的源文件"
    project_drop_ready_source: str = "包含 {COUNT} 个源文件，准备就绪"
    project_select_project_title: str = "选择工程文件"
    project_toast_invalid_lg: str = "请选择 .lg 工程文件"
    project_toast_drop_multi_not_supported: str = "一次只能拖拽一个文件或文件夹"
    project_msg_file_not_found_title: str = "文件不存在"
    project_msg_file_not_found_content: str = (
        "工程文件已被移动或删除："
        "\n"
        "{PATH}"
        "\n"
        "\n"
        "是否从最近打开列表中移除 …?"
    )
    project_msg_close_confirm: str = "确定要关闭当前工程吗 …?"
    project_progress_creating: str = "正在创建工程 …"
    project_progress_loading: str = "正在加载工程 …"
    project_toast_create_fail: str = "创建工程失败：{ERROR}"
    project_toast_load_fail: str = "加载工程失败：{ERROR}"
    project_save_project_title: str = "保存工程文件"
    project_project_ready: str = "项目已就绪"
    project_project_preparing: str = "准备中 …"
    project_info_file_count: str = "文件数量"
    project_info_created_at: str = "创建时间"
    project_info_update: str = "最后修改"
    project_info_progress: str = "翻译进度"
    project_info_translated: str = "已翻译: {COUNT} 行"
    project_info_total: str = "总计: {COUNT} 行"
    project_recent_empty: str = "暂无最近打开的工程"
    project_file_filter_lg: str = "LinguaGacha 工程 (*.lg)"
    project_error_read_preview: str = "读取工程预览失败: {ERROR}"

    # 翻译
    translation_page_status_idle: str = "无任务"
    translation_page_status_translating: str = "翻译中"
    translation_page_status_stopping: str = "停止中"
    translation_page_indeterminate_stopping: str = "正在停止任务 …"
    translation_page_toast_resetting: str = "正在重置 …"
    translation_page_card_time: str = "累计时间"
    translation_page_card_remaining_time: str = "剩余时间"
    translation_page_card_time_tooltip: str = "点击切换 剩余/累计"
    translation_page_card_remaining_line: str = "剩余行数"
    translation_page_card_speed: str = "平均速度"
    translation_page_card_token_input: str = "输入令牌"
    translation_page_card_token_output: str = "输出令牌"
    translation_page_card_token_tooltip: str = "点击切换 输入/输出"
    translation_page_card_line_processed: str = "翻译成功"
    translation_page_card_line_error: str = "翻译失败"
    translation_page_card_line_error_tooltip: str = "一般是网络故障或者接口问题导致"
    translation_page_card_task: str = "实时任务数"
    translation_page_alert_pause: str = "停止的任务可以随时继续执行，是否确定停止任务 …?"
    translation_page_continue: str = "继续"
    translation_page_reset_failed: str = "重置失败条目"
    translation_page_reset_all: str = "重置所有条目"
    translation_page_alert_reset_failed: str = "确定要重置失败条目吗，重置后可以继续翻译 …?"
    translation_page_alert_reset_all: str = "确定要重置所有条目吗，重置后可以继续翻译 …?"
    translation_page_reset_tooltip: str = "点击可选择重置失败条目或全部条目"
    translation_page_timer: str = "请设置延迟启动前要等待的时间"

    # 分析
    analysis_page_status_idle: str = "无任务"
    analysis_page_status_analyzing: str = "分析中"
    analysis_page_status_stopping: str = "停止中"
    analysis_page_indeterminate_stopping: str = "正在停止分析任务 …"
    analysis_page_card_time: str = "累计时间"
    analysis_page_card_remaining_time: str = "剩余时间"
    analysis_page_card_time_tooltip: str = "点击切换 剩余/累计"
    analysis_page_card_line_processed: str = "分析成功"
    analysis_page_card_line_error: str = "分析失败"
    analysis_page_card_line_error_tooltip: str = "一般是网络故障或者接口问题导致"
    analysis_page_card_remaining_line: str = "剩余行数"
    analysis_page_card_speed: str = "平均速度"
    analysis_page_card_token_input: str = "输入令牌"
    analysis_page_card_token_output: str = "输出令牌"
    analysis_page_card_token_tooltip: str = "点击切换 输入/输出"
    analysis_page_card_task: str = "实时任务数"
    analysis_page_alert_pause: str = "停止的分析任务可以随时继续执行，是否确定停止任务 …?"
    analysis_page_continue: str = "继续"
    analysis_page_reset_failed: str = "重置失败条目"
    analysis_page_reset_all: str = "重置全部进度"
    analysis_page_action_import: str = "导入到术语表"
    analysis_page_import_success: str = "导入成功，新增 {COUNT} 条 …"
    analysis_page_alert_reset_failed: str = "确定要重置失败条目吗，重置后可以继续分析 …?"
    analysis_page_alert_reset_all: str = "确定要重置全部分析进度吗，重置后将重新分析全部文本 …?"
    analysis_page_reset_tooltip: str = "点击可选择重置失败条目或全部分析进度"
    analysis_task_source_texts: str = "分析输入："
    analysis_task_extracted_terms: str = "提取术语："
    analysis_task_no_terms: str = "未提取到术语"

    # 校对
    proofreading_page_filter: str = "筛选"
    proofreading_page_replace_action: str = "替换"
    proofreading_page_replace_with_placeholder: str = "替换为 …"
    proofreading_page_replace_btn: str = "替换"
    proofreading_page_replace_all_btn: str = "全部替换"
    proofreading_page_replace_all_confirm: str = "确认执行全部替换 …?"
    proofreading_page_replace_done: str = "替换完成：变更 {N} 条"
    proofreading_page_replace_no_change: str = "没有需要替换的内容"
    proofreading_page_copy_src_done: str = "已复制原文到剪贴板"
    proofreading_page_copy_dst_done: str = "已复制译文到剪贴板"
    proofreading_page_col_status: str = "状态"
    proofreading_page_more: str = "更多"
    proofreading_page_save_failed: str = "保存失败"
    proofreading_page_result_check: str = "结果检查"
    proofreading_page_filter_status: str = "翻译状态"
    proofreading_page_status_none: str = "未翻译"
    proofreading_page_status_processed: str = "翻译完成"
    proofreading_page_status_error: str = "翻译失败"
    proofreading_page_status_processed_in_past: str = "历史完成"
    proofreading_page_status_excluded: str = "已排除"
    proofreading_page_filter_excluded_risk_confirm: str = "此类型的数据绝大部分情况下都不应被翻译，修改前请认真甄别"
    proofreading_page_status_non_target_source_language: str = "非目标原文语言"
    proofreading_page_warning_text_preserve: str = "文本保护失效"
    proofreading_page_warning_similarity: str = "相似度过高"
    proofreading_page_warning_glossary: str = "术语表未生效"
    proofreading_page_warning_retry: str = "重试次数达阈值"
    proofreading_page_glossary_none: str = "无术语"
    proofreading_page_glossary_ok: str = "术语生效"
    proofreading_page_glossary_partial: str = "术语部分生效"
    proofreading_page_glossary_miss: str = "术语全部失效"
    proofreading_page_glossary_tooltip_applied: str = "生效"
    proofreading_page_glossary_tooltip_failed: str = "未生效"
    proofreading_page_filter_select_all: str = "全选"
    proofreading_page_filter_no_warning: str = "无警告"
    proofreading_page_filter_clear: str = "清除"
    proofreading_page_filter_file_scope: str = "文件范围"
    proofreading_page_filter_search_file: str = "按路径搜索文件 …"
    proofreading_page_filter_glossary_detail: str = "未生效术语明细"
    proofreading_page_filter_export_btn: str = "导出报告"
    proofreading_page_filter_export_tooltip: str = "导出当前筛选范围内所有包含结果检查警告的条目"
    proofreading_page_filter_report_title: str = "结果检查报告"
    proofreading_page_filter_report_project: str = "工程"
    proofreading_page_filter_report_time: str = "时间"
    proofreading_page_filter_report_total: str = "总计"
    proofreading_page_filter_report_filter: str = "筛选条件"
    proofreading_page_filter_search_term: str = "搜索术语原文或译文 …"
    proofreading_page_filter_no_glossary_error: str = "当前范围内无术语未生效项"
    proofreading_page_indeterminate_loading: str = "加载数据中 …"
    proofreading_page_indeterminate_saving: str = "保存数据中 …"
    proofreading_page_retranslate: str = "重新翻译"
    proofreading_page_retranslate_confirm: str = "确定重新翻译此条目？"
    proofreading_page_batch_retranslate: str = "重新翻译已选条目"
    proofreading_page_batch_retranslate_confirm: str = "确定重新翻译全部 {COUNT} 个条目？"
    proofreading_page_reset_translation: str = "重置翻译状态"
    proofreading_page_reset_translation_confirm: str = "确定重置此条目的翻译？"
    proofreading_page_batch_reset_translation: str = "重置已选条目翻译状态"
    proofreading_page_batch_reset_translation_confirm: str = (
        "确定重置全部 {COUNT} 个条目的翻译？"
    )

    # 工作台
    workbench_stat_file_count: str = "文件总数"
    workbench_stat_total_lines: str = "总行数"
    workbench_stat_translated: str = "已翻译"
    workbench_stat_untranslated: str = "未翻译"
    workbench_unit_file: str = "File"
    workbench_unit_line: str = "Line"
    workbench_col_file_path: str = "文件名"
    workbench_col_format: str = "格式"
    workbench_col_line_count: str = "行数"
    workbench_col_actions: str = "操作"
    workbench_btn_add_file: str = "添加文件"
    workbench_btn_update: str = "更新"
    workbench_btn_reset: str = "重置"
    workbench_btn_delete: str = "删除"
    workbench_msg_delete_confirm: str = "确定要删除该文件及其所有翻译条目吗 …?"
    workbench_msg_reset_confirm: str = "确定要重置该文件的翻译状态吗 …?"
    workbench_msg_file_exists: str = "文件已存在，请使用更新功能"
    workbench_msg_unsupported_format: str = "不支持的文件格式"
    workbench_msg_update_format_mismatch: str = "文件格式不一致，无法更新"
    workbench_msg_update_confirm: str = "使用所选文件更新当前文件，当前的翻译数据将尽可能的保留"
    workbench_msg_update_name_conflict: str = "{NAME} 已存在 …"
    workbench_fmt_subtitle_file: str = "字幕文件"
    workbench_fmt_text_file: str = "纯文本"
    workbench_fmt_ebook: str = "EPUB"
    workbench_fmt_markdown: str = "Markdown"
    workbench_fmt_renpy: str = "RenPy"
    workbench_fmt_mtool: str = "MTool"
    workbench_fmt_sextractor: str = "VNT/SExtractor"
    workbench_fmt_trans_proj: str = "Translator++"
    workbench_fmt_trans_export: str = "Translator++ XLSX"
    workbench_fmt_wolf: str = "WOLF 官方工具 XLSX"
    workbench_update_stat: str = "新增 {NEW} 条，保留 {MATCHED} 条 …"
    workbench_progress_adding_file: str = "正在添加文件 …"
    workbench_progress_updating_file: str = "正在更新文件 …"
    workbench_progress_resetting_file: str = "正在重置文件 …"
    workbench_progress_deleting_file: str = "正在删除文件 …"
    workbench_msg_file_not_found: str = "文件不存在 …"

    # 基础设置
    basic_settings_page_project_save_mode_title: str = "工程文件保存位置"
    basic_settings_page_project_save_mode_content: str = "设置新建工程时，工程文件的保存位置"
    basic_settings_page_project_save_mode_content_fixed: str = "设置新建工程时，工程文件的保存位置，当前为 {PATH}"
    basic_settings_page_project_save_mode_manual: str = "手动保存"
    basic_settings_page_project_save_mode_fixed: str = "固定路径"
    basic_settings_page_project_save_mode_source: str = "源文件路径"
    basic_settings_page_source_language_title: str = "原文语言"
    basic_settings_page_source_language_content: str = "设置当前项目中输入文本的语言"
    basic_settings_page_source_language_all: str = "全部"
    basic_settings_page_target_language_title: str = "译文语言"
    basic_settings_page_target_language_content: str = "设置当前项目中输出文本的语言"
    basic_settings_page_output_folder_open_on_finish_title: str = "任务完成时打开输出文件夹"
    basic_settings_page_output_folder_open_on_finish_content: str = "启用此功能后，将在任务完成时自动打开输出文件夹"
    basic_settings_page_request_timeout_title: str = "超时时间阈值"
    basic_settings_page_request_timeout_content: str = (
        "发起请求时等待模型回复的最长时间（秒），超时仍未收到回复，则会判断为任务失败"
        ""
        ""
    )

    # 专家设置
    expert_settings_page_preceding_lines_threshold: str = "参考上文行数阈值"
    expert_settings_page_preceding_lines_threshold_desc: str = "每个翻译任务最多可携带的参考上文的行数，默认禁用"
    expert_settings_page_response_check_settings: str = "结果检查规则"
    expert_settings_page_response_check_settings_desc: str = "翻译任务中会根据启用规则检查结果的合法性，默认全部启用"
    expert_settings_page_response_check_settings_button: str = "规则设置"
    expert_settings_page_response_check_kana_residue: str = "假名残留检查"
    expert_settings_page_response_check_hangeul_residue: str = "谚文残留检查"
    expert_settings_page_response_check_similarity: str = "相似度检查"
    expert_settings_page_clean_ruby: str = "清理原文中的注音文本"
    expert_settings_page_clean_ruby_desc: str = (
        "移除注音上标中的注音部分，仅保留正文部分，默认禁用"
        "<br>"
        "文本中的注音上标通常不能被模型正确理解，进行清理可以提升翻译质量，支持的注音格式包括但不限于："
        "<br>"
        "• (漢字/かんじ) [漢字/かんじ] |漢字[かんじ]"
        "<br>"
        "• \\r[漢字,かんじ] \\rb[漢字,かんじ] [r_かんじ][ch_漢字] [ch_漢字]"
        "<br>"
        '• [ruby text=かんじ] [ruby text = かんじ] [ruby text="かんじ"] [ruby text = "かんじ"]'
        ""
        ""
    )
    expert_settings_page_deduplication_in_trans: str = "T++ 项目文件中对重复文本去重"
    expert_settings_page_deduplication_in_trans_desc: str = "在T++ 项目文件（即 <font color='darkgoldenrod'><b>.trans</b></font> 文件）中，如有重复文本是否去重，默认启用"
    expert_settings_page_deduplication_in_bilingual: str = "双语输出文件中原文与译文一致的文本只输出一次"
    expert_settings_page_deduplication_in_bilingual_desc: str = "在字幕与电子书中，如目标文本的原文与译文一致是否只输出一次，默认启用"
    expert_settings_page_write_translated_name_fields_to_file: str = "将姓名字段译文写入输出文件"
    expert_settings_page_write_translated_name_fields_to_file_desc: str = (
        "部分 <font color='darkgoldenrod'><b>GalGame</b></font> 中，姓名字段数据与立绘、配音等资源文件绑定，翻译后会报错，此时可以关闭该功能，默认启用"
        "<br>"
        "支持格式："
        "<br>"
        "• RenPy 导出游戏文本（.rpy）"
        "<br>"
        "• VNTextPatch 或 SExtractor 导出带 name 字段的游戏文本（.json）"
        ""
        ""
    )
    expert_settings_page_auto_process_prefix_suffix_preserved_text: str = "自动处理前后缀的保护文本段"
    expert_settings_page_auto_process_prefix_suffix_preserved_text_desc: str = (
        "是否自动处理每个文本条目头尾命中保护规则的文本段，默认启用"
        "<br>"
        "• 启用后，头尾命中保护规则的文本段将被移除，翻译完成后再拼接回去"
        "<br>"
        "• 禁用后，会将完整的文本条目发送给模型翻译，可能会获得更完整的语义，但会降低文本保护效果"
    )

    # 质量类通用
    quality_import: str = "导入"
    quality_import_toast: str = "数据已导入 …"
    quality_export: str = "导出"
    quality_export_toast: str = "数据已导出 …"
    quality_merge_duplication: str = "已合并重复条目 …"
    quality_delete_confirm: str = "是否确认删除 {COUNT} 条记录？"
    quality_query: str = "查询"
    quality_preset: str = "预设"
    quality_select_file_type: str = "支持的数据格式 (*.json *.xlsx)"
    quality_delete_row: str = "删除行"
    quality_delete_preset: str = "删除预设"
    quality_save_preset: str = "保存预设"
    quality_save_preset_title: str = "保存为预设"
    quality_save_preset_success: str = "预设已保存 …"
    quality_set_as_default_preset: str = "设为默认预设"
    quality_cancel_default_preset: str = "取消默认预设"
    quality_set_default_preset_success: str = "已设置为默认预设 …"
    quality_cancel_default_preset_success: str = "已取消默认预设 …"
    quality_default_preset_loaded_toast: str = "已自动加载默认预设：{NAME} …"
    quality_reorder: str = "排序"
    quality_statistics_action: str = "统计"
    quality_statistics_col_status: str = "状态"
    quality_statistics_tooltip_count: str = "命中条目数：{COUNT}"
    quality_statistics_tooltip_relation_header: str = "存在包含关系："
    quality_statistics_tooltip_relation_line: str = "{CHILD} -> {PARENT}"
    quality_statistics_progress: str = "正在统计规则，第 {CURRENT} 项，共 {TOTAL} 项 …"

    # 规则列
    enable: str = "启用"
    disable: str = "禁用"
    rule_regex: str = "正则表达式"
    rule_case_sensitive: str = "大小写敏感"

    # 术语表
    glossary_page_head_content: str = "通过在提示词中构建术语表来引导模型翻译，可实现统一翻译、矫正人称属性等功能"
    glossary_page_table_row_04: str = "描述"
    glossary_page_kg: str = "一键制作工具"

    # 文本保护
    text_preserve_page_head_content: str = (
        "对文本中无需翻译的代码段、控制字符、样式字符等内容进行保护，避免它们被错误的翻译"
        "<br>"
        "• 关闭 - 不使用任何保护规则，完全交给 AI 执行判断处理"
        "<br>"
        "• 智能 - 自动判断文本格式与游戏引擎选择合适的保护规则"
        "<br>"
        "• 自定义 - 根据本页中设置的 <font color='darkgoldenrod'><b>正则规则</b></font> 匹配对应的文本进行保护"
    )
    text_preserve_mode_off: str = "关闭"
    text_preserve_mode_smart: str = "智能"
    text_preserve_mode_custom: str = "自定义"
    text_preserve_page_table_row_02: str = "备注（仅作备忘，无实际作用）"

    # 译前替换
    pre_translation_replacement_page_head_title: str = "译前替换"
    pre_translation_replacement_page_head_content: str = (
        "在翻译开始前，将原文中匹配的部分替换为指定的文本，执行的顺序为从上到下依次替换"
        "<br>"
        "对于 <font color='darkgoldenrod'><b>RPGMaker MV/MZ</b></font> 引擎的游戏："
        "<br>"
        "• 导入游戏目录的 <font color='darkgoldenrod'><b>data</b></font> 或者 <font color='darkgoldenrod'><b>www\\data</b></font> 文件夹内的 <font color='darkgoldenrod'><b>actors.json</b></font> 文件可以显著提升翻译质量"
        "<br>"
        "• 游戏中包含自定义姓名功能时需要进行特殊处理，请点击右下角按钮跳转并仔细阅读 <font color='darkgoldenrod'><b>Wiki</b></font> 相关页面中的说明"
    )

    # 译后替换
    post_translation_replacement_page_head_title: str = "译后替换"
    post_translation_replacement_page_head_content: str = "在翻译完成后，将译文中匹配的部分替换为指定的文本，执行的顺序为从上到下依次替换"

    # 自定义提示词 - 翻译
    translation_prompt_page_head: str = "自定义翻译提示词（不支持 SakuraLLM 模型）"
    translation_prompt_page_head_desc: str = (
        "通过自定义提示词追加故事设定、行文风格等额外翻译要求"
        "<br>"
        "注意：前缀与后缀部分固定不可修改，只有打开本页开关后，才会在翻译任务中使用这里的正文"
        ""
        ""
    )

    # 自定义提示词 - 分析
    analysis_prompt_page_head: str = "自定义分析提示词"
    analysis_prompt_page_head_desc: str = (
        "通过自定义提示词调整术语分析时的抽取口径和输出要求"
        "<br>"
        "注意：前缀与后缀部分固定不可修改，只有打开本页开关后，才会在分析任务中使用这里的正文"
        ""
        ""
    )

    # 自定义提示词 - 导入导出
    custom_prompt_select_file_type: str = "支持的文件 (*.txt)"

    # 实验室
    laboratory_page_mtool_optimizer_enable: str = "MTool 优化器"
    laboratory_page_mtool_optimizer_enable_desc: str = (
        "在对 MTool 文本进行翻译时，至多可减少 40% 的 翻译时间 与 Token 消耗"
        "<br>"
        "可能导致 <font color='darkgoldenrod'><b>原文残留</b></font> 或 <font color='darkgoldenrod'><b>语句不连贯</b></font> 等问题，请 <font color='darkgoldenrod'><b>自行判断</b></font> 是否启用，并且只应在 <font color='darkgoldenrod'><b>翻译 MTool 文本时</b></font> 启用"
        ""
        ""
        ""
        ""
        ""
        ""
    )
    laboratory_page_force_thinking_enable: str = "强制思考"
    laboratory_page_force_thinking_enable_desc: str = (
        "启用后，非思考模型在翻译前也会进行思考，默认启用，请注意：此功能不支持 SakuraLLM 模型"
        "<br>"
        "◈ 通过略微增加 Token 消耗换取翻译效果的提升"
        "<br>"
        "◈ 不建议在思考类模型上启用，重复思考意义不大"
        "<br>"
        "◈ 正常生效时，会在翻译日志中观察到模型思考内容的输出"
    )
    laboratory_page_auto_glossary_enable: str = "自动补全术语表"
    laboratory_page_auto_glossary_enable_desc: str = (
        "边翻译边补全术语表，默认禁用，请注意：此功能不支持 SakuraLLM 模型"
        "<br>"
        "◈ 仅供查漏补缺，可能会产生 <font color='darkgoldenrod'><b>不正确或不恰当</b></font> 的数据"
        "<br>"
        "◈ 建议在使用 <font color='darkgoldenrod'><b>KeywordGacha</b></font> 获得完整的、经过筛选的术语表的基础上启用此功能"
    )

    # 百宝箱
    tool_box_page_name_field_extraction_desc: str = (
        "提取 <font color='darkgoldenrod'><b>RenPy</b></font> 和 <font color='darkgoldenrod'><b>GalGame</b></font> 游戏文本中的角色姓名字段数据，"
        "自动生成对应的术语表数据，方便后续进行翻译"
    )
    tool_box_page_ts_conversion: str = "繁简转换"
    tool_box_page_ts_conversion_desc: str = "对当前项目的译文或角色名称进行批量繁简转换，支持文本保护"

    # 百宝箱 - 姓名字段提取
    name_field_extraction_page: str = "姓名字段提取"
    name_field_extraction_page_desc: str = (
        "将从 <font color='darkgoldenrod'><b>输入文件夹</b></font> 中所有符合条件的文件中提取角色姓名字段，自动生成对应的术语表数据"
        "<br>"
        "请注意：此功能 <font color='darkgoldenrod'><b>不能提取正文内的术语</b></font>，不能代替 <font color='darkgoldenrod'><b>KeywordGacha</b></font> 工具"
        "<br>"
        "支持格式："
        "<br>"
        "• RenPy 导出游戏文本（.rpy）"
        "<br>"
        "• VNTextPatch 或 SExtractor 导出带 name 字段的游戏文本（.json）"
    )
    name_field_extraction_action_extract: str = "提取"
    name_field_extraction_action_translate: str = "翻译"
    name_field_extraction_action_import: str = "导入到术语表"
    name_field_extraction_action_progress: str = "正在提取姓名字段 …"
    name_field_extraction_context: str = "上下文"

    # 百宝箱 - 繁简转换
    ts_conversion_page: str = "繁简转换"
    ts_conversion_page_desc: str = "将项目中的译文在简体中文和繁体中文之间转换"
    ts_conversion_direction: str = "转换模式"
    ts_conversion_direction_desc: str = "简繁转换功能由 OpenCC 实现，简体到繁体使用 S2TW 规则，繁体到简体使用 T2S 规则"
    ts_conversion_to_traditional: str = "简体到繁体"
    ts_conversion_to_simplified: str = "繁体到简体"
    ts_conversion_target_name: str = "转换姓名字段译文"
    ts_conversion_target_name_desc: str = (
        "部分 <font color='darkgoldenrod'><b>GalGame</b></font> 中，姓名字段数据与立绘、配音等资源文件绑定，翻译后会报错，此时可以关闭该功能，默认启用"
        ""
        ""
    )
    ts_conversion_preserve_text: str = "遵循文本保护规则"
    ts_conversion_preserve_text_desc: str = "遵循文本保护规则，避免翻译过程中破坏游戏文本中的代码段"
    ts_conversion_action_start: str = "开始转换"
    ts_conversion_action_confirm: str = "是否开始执行简繁转换 …?"
    ts_conversion_action_progress: str = "正在执行简繁转换，第 {CURRENT} 项，共 {TOTAL} 项 …"
    ts_conversion_action_preparing: str = "正在准备简繁转换数据 …"
