from module.Localizer.LocalizerZH import LocalizerZH


class LocalizerEN(LocalizerZH):
    # 保留
    switch_language: str = (
        "请选择应用语言，新的语言设置将在下次启动时生效 …"
        "\n"
        "Select application language, changes will take effect on restart …"
    )
    switch_language_toast: str = (
        "应用语言切换成功，请重启应用生效 …"
        "\n"
        "Language switched successfully, please restart the application for changes to take effect …"
    )

    # 通用
    add: str = "Add"
    edit: str = "Edit"
    delete: str = "Delete"
    rename: str = "Rename"
    select_file: str = "Select File"
    select_folder: str = "Select Folder"
    supported_files: str = "Supported Files"
    back: str = "Back"
    stop: str = "Stop"
    start: str = "Start"
    save: str = "Save"
    timer: str = "Timer"
    reset: str = "Reset"
    basic_settings: str = "Basic Settings"
    api_url: str = "API URL"
    table_col_source: str = "Source"
    table_col_translation: str = "Translation"
    table_col_replacement: str = "Replacement"
    table_col_rule: str = "Rule"
    status: str = "Current Status: "
    status_enabled: str = "Current Status: Enabled"
    status_disabled: str = "Current Status: Disabled"
    issue_kana_residue: str = "Kana Residue"
    issue_hangeul_residue: str = "Hangeul Residue"
    close: str = "Close"
    alert: str = "Alert"
    warning: str = "Warning"
    confirm: str = "Confirm"
    cancel: str = "Cancel"
    auto: str = "Auto"
    wiki: str = "Wiki"
    view_more_info: str = "View more info"
    filter: str = "Filter"
    search: str = "Search"
    placeholder: str = "Please enter keywords …"
    task_failed: str = "Task failed …"
    task_success: str = "Task succeeded …"
    task_running: str = "Task is running …"
    task_batch_translation_progress: str = "Translating, item {CURRENT} of {TOTAL} …"
    task_batch_translation_success: str = "Translation completed, {SUCCESS} successful, {FAILED} failed …"
    toast_save: str = "Saved …"
    toast_reset: str = "Reseted …"
    toast_processing: str = "Processing …"
    move_up: str = "Move Up"
    move_down: str = "Move Down"
    move_top: str = "Move To Top"
    move_bottom: str = "Move To Bottom"
    export_translation: str = "Generate"
    export_translation_confirm: str = "Confirm to generate the translation file?"
    export_translation_start: str = "Generating translation …"
    export_translation_done: str = "Translation files saved to [blue]{PATH}[/blue] …"
    export_translation_success: str = "Translation files generated …"
    export_translation_failed: str = "Failed to generate translation files …"
    alert_no_data: str = "No valid data …"
    alert_project_not_loaded: str = "Please load a project first …"
    alert_no_active_model: str = "No active model configuration found …"
    alert_confirm_reset_data: str = "Confirm reset data …?"
    alert_confirm_delete_data: str = "Confirm delete data …?"
    alert_reset_timer: str = "Confirm to reset timer?"
    alert_file_already_exists: str = "File already exists …"
    alert_preset_already_exists: str = "Preset already exists, confirm overwrite …?"
    search_prev_btn: str = "Previous"
    search_next_btn: str = "Next"
    search_prev_match: str = "Previous match"
    search_next_match: str = "Next match"
    search_regex_on: str = (
        "Regex Mode"
        "\n"
        "Current Status: Enabled"
    )
    search_regex_off: str = (
        "Regex Mode"
        "\n"
        "Current Status: Disabled"
    )
    search_regex_invalid: str = "Invalid regular expression"
    search_no_match: str = "No matches found"
    search_regex_btn: str = "Regex"
    search_match_info: str = "Item {current} of {total}"
    search_no_result: str = "No results"
    shortcut_ctrl_s: str = "Ctrl+S"

    # 主页面
    app_close_message_box: str = "Are you sure you want to exit the application …?"
    app_exit_countdown: str = "Exiting … {SECONDS} …"
    app_new_version: str = "Download New Version!"
    app_new_version_toast: str = "New version found, version: {VERSION}. Please click the button on the bottom left to download and update …"
    app_new_version_update: str = "Downloading {PERCENT} …"
    app_new_version_failure: str = "New version download failed …"
    app_new_version_success: str = "New version download successful …"
    app_new_version_downloaded: str = "Click to apply New Version!"
    app_new_version_applying: str = "Applying update …"
    app_new_version_apply_failed: str = "Update failed and rolled back …"
    app_new_version_waiting_restart: str = "Update completed, application will close soon …"
    app_project_closed_toast: str = "Current project closed …"
    app_close_project_btn: str = "Close Project"
    app_theme_btn: str = "Theme"
    app_language_btn: str = "Language"
    app_settings_page: str = "App Settings"
    app_model_page: str = "Model"
    app_translation_page: str = "Translation"
    app_analysis_page: str = "Analysis"
    app_proofreading_page: str = "Proofreading"
    app_workbench_page: str = "Workbench"
    app_expert_settings_page: str = "Expert Settings"
    app_glossary_page: str = "Glossary"
    app_text_preserve_page: str = "Text Preserve"
    app_text_replacement_page: str = "Text Replacement"
    app_pre_translation_replacement_page: str = "Pre-Translation"
    app_post_translation_replacement_page: str = "Post-Translation"
    app_custom_prompt_navigation_item: str = "Custom Prompts"
    app_analysis_prompt_page: str = "Analysis Prompts"
    app_translation_prompt_page: str = "Translation Prompts"
    app_laboratory_page: str = "Laboratory"
    app_treasure_chest_page: str = "Treasure Chest"

    # 路径
    path_translated: str = "Translated"
    path_translated_bilingual: str = "Translated_Bilingual"

    # 日志
    log_crash: str = "A critical error has occurred, app will now exit, error detail has been saved to the log file …"
    log_proxy: str = "Network proxy enabled …"
    log_expert_mode: str = "Expert Mode Enabled …"
    log_api_test_fail: str = (
        "API test failed …"
        "\n"
        "Reason: {REASON}"
    )
    log_read_file_fail: str = "File reading failed …"
    log_write_file_fail: str = "File writing failed …"
    log_unknown_reason: str = "Unknown Reason"
    log_cli_verify_language: str = "parameter error: invalid language …"
    log_cli_target_language_all_unsupported: str = "ALL is not supported …"
    log_cli_quality_rule_file_not_found: str = (
        "parameter error: rule file not found …"
        "\n"
        "Argument: {ARG}"
        "\n"
        "Path: {PATH}"
    )
    log_cli_quality_rule_file_unsupported: str = (
        "parameter error: unsupported rule file format (only .json/.xlsx) …"
        "\n"
        "Argument: {ARG}"
        "\n"
        "Path: {PATH}"
    )
    log_cli_quality_rule_import_failed: str = (
        "quality rule import failed …"
        "\n"
        "Argument: {ARG}"
        "\n"
        "Path: {PATH}"
        "\n"
        "Reason: {REASON}"
    )
    log_cli_text_preserve_mode_invalid: str = (
        "parameter error: invalid text preserve options …"
        "\n"
        "--text_preserve_mode: {MODE}"
        "\n"
        "--text_preserve: {PATH}"
        "\n"
        "Note: mode=custom requires --text_preserve; providing --text_preserve requires mode=custom"
    )

    # 引擎
    engine_no_items: str = "No items to process were found, please check …"
    engine_task_done: str = "Task completed …"
    engine_task_fail: str = "Task failed to complete, some data remains unprocessed. Please check the results …"
    engine_task_stop: str = "Task stopped …"
    engine_task_rule_filter: str = "Rule filtering completed, {COUNT} entries that do not require translation were filtered in total …"
    engine_task_language_filter: str = "Language filtering completed, {COUNT} non-target source language entries were skipped in total …"
    engine_task_scheduler_stop_with_untranslated: str = "Task scheduler stopped, but {COUNT} items remain untranslated (potentially lost due to exceptions)"
    engine_task_simple_log_prefix: str = "Simple Log"
    engine_task_success: str = "Task time {TIME} seconds, {LINES} lines of text, input tokens {PT}, output tokens {CT}"
    engine_task_response_think: str = "Model Thinking:"
    engine_task_response_result: str = "Model Response:"
    translation_task_status_info: str = "Split: {SPLIT} | Retry: {RETRY} | Task Length Threshold: {THRESHOLD}"
    translation_task_force_accept_info: str = " | Forced Accept: {REASON}"
    engine_api_name: str = "API Name"
    engine_api_model: str = "API Model"
    api_test_key: str = "Testing Key:"
    api_test_messages: str = "Task Prompts:"
    api_test_timeout: str = "Request timed out ({SECONDS}s)"
    api_test_result: str = "Tested {COUNT} APIs in total, {SUCCESS} successful, {FAILURE} failed …"
    api_test_result_failure: str = "Failed Keys:"
    api_test_token_info: str = "Token usage: input {INPUT}, output {OUTPUT}, time {TIME}s"
    translation_mtool_optimizer_pre_log: str = "MToolOptimizer pre-processing completed, {COUNT} entries containing duplicate clauses were filtered in total …"
    translation_mtool_optimizer_post_log: str = "MToolOptimizer post-processing completed …"
    translation_response_check_fail: str = "Data error, will automatically retry, Reason: {REASON}"
    translation_response_check_fail_all: str = "All translated text quality check failed, will automatically split and retry, Reason: {REASON}"
    translation_response_check_fail_part: str = "Partial translated text quality check failed, will automatically split and retry, Reason: {REASON}"
    translation_response_check_fail_force: str = "Translation check failed"
    response_checker_fail_data: str = "Data Structure Error"
    response_checker_fail_timeout: str = "Network Request Timeout"
    response_checker_fail_line_count: str = "Line Count Mismatch"
    response_checker_fail_degradation: str = "Degradation Occurred"
    response_checker_line_error_empty_line: str = "Empty Line"
    response_checker_line_error_similarity: str = "High Similarity"
    project_store_ingesting_assets: str = "Ingesting assets …"
    project_store_ingesting_file: str = "Ingesting assets: {NAME}"
    project_store_parsing_items: str = "Parsing translation items …"
    project_store_created: str = "Project creation completed …"
    project_store_file_not_found: str = "Project file not found: {PATH}"

    # 应用设置
    app_settings_page_expert_title: str = "Expert Mode"
    app_settings_page_expert_content: str = "Enabling this feature will display more log information and provide more advanced setting options (takes effect after app restart)"
    app_settings_page_scale_factor_title: str = "Global Scale Factor"
    app_settings_page_scale_factor_content: str = "Enabling this feature will scale the app interface according to the selected ratio (takes effect after app restart)"
    app_settings_page_proxy_url: str = "Example - http://127.0.0.1:7890"
    app_settings_page_proxy_url_title: str = "Network Proxy"
    app_settings_page_proxy_url_content: str = "Enabling this feature will use the set proxy address to send network requests  (takes effect after app restart)"
    app_settings_page_close: str = "The application will close, please confirm …"

    # 模型管理
    model_page_activate: str = "Activate Model"
    model_page_task_setting: str = "Task Settings"
    model_page_advanced_setting: str = "Advanced Settings"
    model_page_test: str = "Test Model"
    model_page_adjust_order: str = "Adjust Order"
    model_page_delete: str = "Delete Model"
    model_page_reset: str = "Reset Model"
    model_page_category_preset_title: str = "Preset Models"
    model_page_category_preset_desc: str = "Built-in preset models of the application"
    model_page_category_google_title: str = "Custom Google Models"
    model_page_category_google_desc: str = "Custom models compatible with Google Gemini API format"
    model_page_category_openai_title: str = "Custom OpenAI Models"
    model_page_category_openai_desc: str = "Custom models compatible with OpenAI API format"
    model_page_category_anthropic_title: str = "Custom Anthropic Models"
    model_page_category_anthropic_desc: str = "Custom models compatible with Anthropic Claude API format"
    model_page_migrated_toast: str = "Detected {COUNT} deprecated preset models, automatically migrated to custom model categories …"
    model_page_delete_last_one_toast: str = "At least one model must be kept in each category, cannot delete …"
    model_page_reset_success_toast: str = "Model reset successfully …"
    model_basic_setting_page_name: str = "Please enter model name …"
    model_basic_setting_page_name_title: str = "Model Name"
    model_basic_setting_page_name_content: str = "Please enter model name, only for display within the app, no practical effect"
    model_basic_setting_page_api_url: str = "Please enter API URL …"
    model_basic_setting_page_api_url_content: str = "Please enter API URL, pay attention to whether /v1 needs to be added at the end"
    model_basic_setting_page_api_key: str = "Please enter API Key …"
    model_basic_setting_page_api_key_title: str = "API Key"
    model_basic_setting_page_api_key_content: str = "Please enter API Key, e.g., sk-d0daba12345678fd8eb7b8d31c123456. Multiple keys can be entered for polling, one key per line"
    model_basic_setting_page_model_id: str = "Please enter model identifier …"
    model_basic_setting_page_model_id_title: str = "Model Identifier"
    model_basic_setting_page_model_id_content: str = "Current model identifier: {MODEL}"
    model_basic_setting_page_model_id_edit: str = "Manual Input"
    model_basic_setting_page_model_id_sync: str = "Fetch Online"
    model_basic_setting_page_model_id_input: str = "Input"
    model_basic_setting_page_model_id_fetch: str = "Fetch"
    model_basic_setting_page_model_id_test: str = "Test"
    model_basic_setting_page_thinking_title: str = "Thinking Level"
    model_basic_setting_page_thinking_content: str = "Configure thinking level which will affect time and cost, click question icon for supported models"
    model_basic_setting_page_thinking_off: str = "Off"
    model_basic_setting_page_thinking_low: str = "Low"
    model_basic_setting_page_thinking_medium: str = "Medium"
    model_basic_setting_page_thinking_high: str = "High"
    model_basic_setting_page_input_token_title: str = "Input Token Limit"
    model_basic_setting_page_input_token_content: str = "Maximum number of tokens for each task input"
    model_basic_setting_page_output_token_title: str = "Output Token Limit"
    model_basic_setting_page_output_token_content: str = "Maximum number of tokens for each task output, 0 = Automatic"

    model_basic_setting_page_rpm_title: str = "Requests Per Minute Limit (RPM)"
    model_basic_setting_page_rpm_content: str = (
        "Maximum total number of tasks executed per minute, i.e., the <font color='darkgoldenrod'><b>RPM</b></font> limit"
        "<br>"
        "Some platforms may limit the request rate"
        "<br>"
        "Please refer to the API platform's documentation for settings, 0 = unlimited"
    )
    model_basic_setting_page_concurrency_title: str = "Concurrent Task Limit"
    model_basic_setting_page_concurrency_content: str = (
        "Maximum number of tasks executing simultaneously"
        "<br>"
        "Proper configuration can significantly speed up task completion"
        "<br>"
        "Please refer to the API platform's documentation for settings, 0 = Automatic"
    )
    model_advanced_setting_page_headers_title: str = "Custom Request Headers"
    model_advanced_setting_page_headers_content: str = "Custom request header parameters, please set with caution, incorrect values may cause abnormal results or request errors"
    model_advanced_setting_page_headers_placeholder: str = 'Example: {"Authorization": "Bearer xxx"}'
    model_advanced_setting_page_body_title: str = "Custom Request Body"
    model_advanced_setting_page_body_content: str = "Custom request body parameters, please set with caution, incorrect values may cause abnormal results or request errors"
    model_advanced_setting_page_body_placeholder: str = 'Example: {"seed": 42}'
    model_advanced_setting_page_param_caution: str = "Please set with caution, incorrect values may cause abnormal results or request errors"
    model_advanced_setting_page_top_p_title: str = "top_p"
    model_advanced_setting_page_temperature_title: str = "temperature"
    model_advanced_setting_page_presence_penalty_title: str = "presence_penalty"
    model_advanced_setting_page_frequency_penalty_title: str = "frequency_penalty"
    model_advanced_setting_page_json_format_error: str = "JSON format error, please enter a valid JSON object"
    model_selector_page_title: str = "Available Model List"
    model_selector_page_content: str = "Click to select the model to use"
    model_selector_page_fail: str = "Failed to get model list, please check API configuration …"
    model_selector_page_loading: str = "Loading model list …"

    # 工程页
    project_new_project_title: str = "New Project"
    project_new_project_subtitle: str = "Select source files to create a self-contained .lg project."
    project_new_project_btn: str = "Create Project"
    project_open_project_title: str = "Open Project"
    project_open_project_subtitle: str = "Load a .lg project to continue with saved progress and rules."
    project_recent_projects_title: str = "Recent Projects"
    project_drop_zone_source_title: str = "Click or Drag Source File"
    project_drop_zone_lg_title: str = "Click or Drag .lg File"
    project_fmt_title: str = "Supported File Formats"
    project_fmt_subtitle: str = "Subtitle"
    project_fmt_ebook: str = "E-book"
    project_fmt_markdown: str = "Markdown"
    project_fmt_renpy: str = "RenPy Game Text"
    project_fmt_mtool: str = "MTool Game Text"
    project_fmt_sextractor: str = "SExtractor Game Text"
    project_fmt_vntextpatch: str = "VNTextPatch Game Text"
    project_fmt_trans_proj: str = "Translator++ Project File"
    project_fmt_trans_export: str = "Translator++ Game Text"
    project_fmt_wolf: str = "WOLF Offical Tool Game Text"
    project_select_source_dir_title: str = "Select Source Directory"
    project_toast_no_valid_file: str = "No supported source files found in this directory"
    project_drop_ready_source: str = "{COUNT} source files found, ready"
    project_select_project_title: str = "Select Project File"
    project_toast_invalid_lg: str = "Please select a .lg project file"
    project_toast_drop_multi_not_supported: str = "Only one file or folder can be dropped at a time"
    project_msg_file_not_found_title: str = "File Not Found"
    project_msg_file_not_found_content: str = (
        "Project file has been moved or deleted:"
        "\n"
        "{PATH}"
        "\n"
        "\n"
        "Remove from recent list?"
    )
    project_msg_close_confirm: str = "Are you sure you want to close the current project?"
    project_progress_creating: str = "Creating project …"
    project_progress_loading: str = "Loading project …"
    project_toast_create_fail: str = "Failed to create project: {ERROR}"
    project_toast_load_fail: str = "Failed to load project: {ERROR}"
    project_save_project_title: str = "Save Project File"
    project_project_ready: str = "Project Ready"
    project_project_preparing: str = "Preparing …"
    project_info_file_count: str = "File Count"
    project_info_created_at: str = "Created At"
    project_info_update: str = "Last Updated"
    project_info_progress: str = "Progress"
    project_info_translated: str = "Translated: {COUNT}"
    project_info_total: str = "Total: {COUNT}"
    project_recent_empty: str = "No recent projects"
    project_file_filter_lg: str = "LinguaGacha Project (*.lg)"
    project_error_read_preview: str = "Failed to read project preview: {ERROR}"

    # 翻译
    translation_page_status_idle: str = "Idle"
    translation_page_status_translating: str = "Translating"
    translation_page_status_stopping: str = "Stopping"
    translation_page_indeterminate_stopping: str = "Stopping task …"
    translation_page_toast_resetting: str = "Resetting …"
    translation_page_card_time: str = "Elapsed Time"
    translation_page_card_remaining_time: str = "Remaining Time"
    translation_page_card_time_tooltip: str = "Click to toggle Remaining/Elapsed"
    translation_page_card_remaining_line: str = "Remaining Lines"
    translation_page_card_speed: str = "Average Speed"
    translation_page_card_token_input: str = "Input Tokens"
    translation_page_card_token_output: str = "Output Tokens"
    translation_page_card_token_tooltip: str = "Click to toggle Input/Output"
    translation_page_card_line_processed: str = "Succeeded"
    translation_page_card_line_error: str = "Failed"
    translation_page_card_line_error_tooltip: str = "Usually caused by network failure or api issues"
    translation_page_card_task: str = "Real Time Tasks"
    translation_page_alert_pause: str = "Stopped tasks can be resumed at any time. Confirm to stop the task …?"
    translation_page_continue: str = "Continue"
    translation_page_reset_failed: str = "Reset Failed Items"
    translation_page_reset_all: str = "Reset All Items"
    translation_page_alert_reset_failed: str = "Confirm to reset failed items? You can continue translating after reset …?"
    translation_page_alert_reset_all: str = "Confirm to reset all items? You can continue translating after reset …?"
    translation_page_reset_tooltip: str = "Click to choose resetting failed items or all items"
    translation_page_timer: str = "Waiting time before delayed startup"

    # 分析
    analysis_page_status_idle: str = "Idle"
    analysis_page_status_analyzing: str = "Analyzing"
    analysis_page_status_stopping: str = "Stopping"
    analysis_page_indeterminate_stopping: str = "Stopping analysis task …"
    analysis_page_card_time: str = "Elapsed Time"
    analysis_page_card_remaining_time: str = "Remaining Time"
    analysis_page_card_time_tooltip: str = "Click to toggle Remaining/Elapsed"
    analysis_page_card_line_processed: str = "Analyzed"
    analysis_page_card_line_error: str = "Failed"
    analysis_page_card_line_error_tooltip: str = "Usually caused by network failure or api issues"
    analysis_page_card_remaining_line: str = "Remaining Lines"
    analysis_page_card_speed: str = "Average Speed"
    analysis_page_card_token_input: str = "Input Tokens"
    analysis_page_card_token_output: str = "Output Tokens"
    analysis_page_card_token_tooltip: str = "Click to toggle Input/Output"
    analysis_page_card_task: str = "Real Time Tasks"
    analysis_page_alert_pause: str = "Stopped analysis tasks can be resumed at any time. Confirm to stop the task …?"
    analysis_page_continue: str = "Continue"
    analysis_page_reset_failed: str = "Reset Failed Items"
    analysis_page_reset_all: str = "Reset All Progress"
    analysis_page_action_import: str = "Import To Glossary"
    analysis_page_import_success: str = "Import succeeded, added {COUNT} entries …"
    analysis_page_alert_reset_failed: str = "Confirm to reset failed items? You can continue analyzing after reset …?"
    analysis_page_alert_reset_all: str = "Confirm to reset all analysis progress? The whole project text will be analyzed again after reset …?"
    analysis_page_reset_tooltip: str = "Click to choose resetting failed items or all analysis progress"
    analysis_task_source_texts: str = "Analysis Input:"
    analysis_task_extracted_terms: str = "Extracted Terms:"
    analysis_task_no_terms: str = "No terms extracted"

    # 校对
    proofreading_page_filter: str = "Filter"
    proofreading_page_replace_action: str = "Replace"
    proofreading_page_replace_with_placeholder: str = "Replace with …"
    proofreading_page_replace_btn: str = "Replace"
    proofreading_page_replace_all_btn: str = "Replace All"
    proofreading_page_replace_all_confirm: str = "Confirm to replace all …?"
    proofreading_page_replace_done: str = "Replace complete: changed {N} items"
    proofreading_page_replace_no_change: str = "No content to replace"
    proofreading_page_copy_src_done: str = "Source copied to clipboard"
    proofreading_page_copy_dst_done: str = "Translation copied to clipboard"
    proofreading_page_col_status: str = "Status"
    proofreading_page_more: str = "More"
    proofreading_page_save_failed: str = "Save failed"
    proofreading_page_result_check: str = "Result Check"
    proofreading_page_filter_status: str = "Translation Status"
    proofreading_page_status_none: str = "Untranslated"
    proofreading_page_status_processed: str = "Translation Completed"
    proofreading_page_status_error: str = "Translation Failed"
    proofreading_page_status_processed_in_past: str = "Previously Completed"
    proofreading_page_status_excluded: str = "Excluded"
    proofreading_page_filter_excluded_risk_confirm: str = "Mostly shouldn't be translated, identify carefully before modifying"
    proofreading_page_status_non_target_source_language: str = "Non-target source language"
    proofreading_page_warning_text_preserve: str = "Text Preserve Failed"
    proofreading_page_warning_similarity: str = "High Similarity"
    proofreading_page_warning_glossary: str = "Glossary Not Applied"
    proofreading_page_warning_retry: str = "Retry Threshold Reached"
    proofreading_page_glossary_none: str = "No Term"
    proofreading_page_glossary_ok: str = "Glossary Applied"
    proofreading_page_glossary_partial: str = "Glossary Partially Applied"
    proofreading_page_glossary_miss: str = "Glossary All Failed"
    proofreading_page_glossary_tooltip_applied: str = "Applied"
    proofreading_page_glossary_tooltip_failed: str = "Not Applied"
    proofreading_page_filter_select_all: str = "Select All"
    proofreading_page_filter_no_warning: str = "No Warning"
    proofreading_page_filter_clear: str = "Clear"
    proofreading_page_filter_file_scope: str = "File Scope"
    proofreading_page_filter_search_file: str = "Search files by path …"
    proofreading_page_filter_glossary_detail: str = "Glossary Error Details"
    proofreading_page_filter_export_btn: str = "Export Report"
    proofreading_page_filter_export_tooltip: str = "Export all items with warnings in the current filter scope"
    proofreading_page_filter_report_title: str = "Result Check Report"
    proofreading_page_filter_report_project: str = "Project"
    proofreading_page_filter_report_time: str = "Time"
    proofreading_page_filter_report_total: str = "Total"
    proofreading_page_filter_report_filter: str = "Filter"
    proofreading_page_filter_search_term: str = "Search term source or target …"
    proofreading_page_filter_no_glossary_error: str = "No glossary errors in current scope"
    proofreading_page_indeterminate_loading: str = "Loading data …"
    proofreading_page_indeterminate_saving: str = "Saving data …"
    proofreading_page_retranslate: str = "Retranslate"
    proofreading_page_retranslate_confirm: str = "Retranslate this entry?"
    proofreading_page_batch_retranslate: str = "Retranslate selected"
    proofreading_page_batch_retranslate_confirm: str = "Retranslate all {COUNT} entries?"
    proofreading_page_reset_translation: str = "Reset Translation"
    proofreading_page_reset_translation_confirm: str = "Reset translation for this entry?"
    proofreading_page_batch_reset_translation: str = "Reset Selected"
    proofreading_page_batch_reset_translation_confirm: str = (
        "Reset translation for all {COUNT} entries?"
    )

    # 工作台
    workbench_stat_file_count: str = "Files"
    workbench_stat_total_lines: str = "Total Lines"
    workbench_stat_translated: str = "Translated"
    workbench_stat_untranslated: str = "Untranslated"
    workbench_unit_file: str = "File"
    workbench_unit_line: str = "Line"
    workbench_col_file_path: str = "File Name"
    workbench_col_format: str = "Format"
    workbench_col_line_count: str = "Lines"
    workbench_col_actions: str = "Actions"
    workbench_btn_add_file: str = "Add File"
    workbench_btn_update: str = "Update"
    workbench_btn_reset: str = "Reset"
    workbench_btn_delete: str = "Delete"
    workbench_msg_delete_confirm: str = "Delete this file and all its translation items …?"
    workbench_msg_reset_confirm: str = "Reset translation status for this file …?"
    workbench_msg_file_exists: str = "File already exists, please use Update"
    workbench_msg_unsupported_format: str = "Unsupported file format"
    workbench_msg_update_format_mismatch: str = "File format mismatch, cannot update"
    workbench_msg_update_confirm: str = "Update the current file with the selected file, current data will be preserved as possible"
    workbench_msg_update_name_conflict: str = "{NAME} already exists …"
    workbench_fmt_subtitle_file: str = "Subtitle File"
    workbench_fmt_text_file: str = "Plain Text"
    workbench_fmt_ebook: str = "EPUB"
    workbench_fmt_markdown: str = "Markdown"
    workbench_fmt_renpy: str = "RenPy"
    workbench_fmt_mtool: str = "MTool"
    workbench_fmt_sextractor: str = "VNT/SExtractor"
    workbench_fmt_trans_proj: str = "Translator++"
    workbench_fmt_trans_export: str = "Translator++ XLSX"
    workbench_fmt_wolf: str = "WOLF Official Tool XLSX"
    workbench_update_stat: str = "Added {NEW}, kept {MATCHED} …"
    workbench_progress_adding_file: str = "Adding file ..."
    workbench_progress_updating_file: str = "Updating file ..."
    workbench_progress_resetting_file: str = "Resetting file ..."
    workbench_progress_deleting_file: str = "Deleting file ..."
    workbench_msg_file_not_found: str = "File not found"

    # 基础设置
    basic_settings_page_project_save_mode_title: str = "Project File Save Location"
    basic_settings_page_project_save_mode_content: str = "Set the save location for project files when creating a new project"
    basic_settings_page_project_save_mode_content_fixed: str = "Set the save location for project files when creating a new project, currently {PATH}"
    basic_settings_page_project_save_mode_manual: str = "Manual Save"
    basic_settings_page_project_save_mode_fixed: str = "Fixed Path"
    basic_settings_page_project_save_mode_source: str = "Source File Path"
    basic_settings_page_source_language_title: str = "Source Language"
    basic_settings_page_source_language_content: str = "Set the language of the input text in the current project"
    basic_settings_page_source_language_all: str = "All"
    basic_settings_page_target_language_title: str = "Target Language"
    basic_settings_page_target_language_content: str = "Set the language of the output text in the current project"
    basic_settings_page_output_folder_open_on_finish_title: str = "Open Output Folder on Task Completion"
    basic_settings_page_output_folder_open_on_finish_content: str = "When enabled, the output folder will be automatically opened upon task completion"
    basic_settings_page_request_timeout_title: str = "Request Timeout"
    basic_settings_page_request_timeout_content: str = (
        "The maximum time (seconds) to wait for the model's response when making a request"
        "<br>"
        "If no reply is received after the timeout, the task will be considered failed"
    )

    # 专家设置
    expert_settings_page_preceding_lines_threshold: str = "Preceding Lines Threshold"
    expert_settings_page_preceding_lines_threshold_desc: str = "Maximum number of preceding lines to include as context for each translation task, disabled by default"
    expert_settings_page_response_check_settings: str = "Result Check Rules"
    expert_settings_page_response_check_settings_desc: str = "In translation tasks, the validity of results is checked based on enabled rules, all enabled by default"
    expert_settings_page_response_check_settings_button: str = "Rules Settings"
    expert_settings_page_response_check_kana_residue: str = "Kana Residue Check"
    expert_settings_page_response_check_hangeul_residue: str = "Hangeul Residue Check"
    expert_settings_page_response_check_similarity: str = "Similarity Check"
    expert_settings_page_clean_ruby: str = "Clean Ruby Text"
    expert_settings_page_clean_ruby_desc: str = (
        "Removes the phonetic ruby characters from annotations, retaining only the main text, disabled by default"
        "<br>"
        "Ruby annotations in text are often not correctly understood by the model, cleaning them can improve translation quality"
        "<br>"
        "Supported ruby formats include, but are not limited to:"
        "<br>"
        "• (漢字/かんじ) [漢字/かんじ] |漢字[かんじ]"
        "<br>"
        "• \\r[漢字,かんじ] \\rb[漢字,かんじ] [r_かんじ][ch_漢字] [ch_漢字]"
        "<br>"
        '• [ruby text=かんじ] [ruby text = かんじ] [ruby text="かんじ"] [ruby text = "かんじ"]'
    )
    expert_settings_page_deduplication_in_trans: str = "Deduplicate Repeated Text in T++ Project File"
    expert_settings_page_deduplication_in_trans_desc: str = "In T++ project file (i.e., <font color='darkgoldenrod'><b>.trans</b></font> file), whether to deduplicate repeated text, enabled by default"
    expert_settings_page_deduplication_in_bilingual: str = "Output Only Once if Source and Target are Identical in Bilingual Output Files"
    expert_settings_page_deduplication_in_bilingual_desc: str = "In subtitles or e-books, whether to output text only once if the source and target text are identical, enabled by default"
    expert_settings_page_write_translated_name_fields_to_file: str = "Write Translated Name Fields to the Output File"
    expert_settings_page_write_translated_name_fields_to_file_desc: str = (
        "In some <font color='darkgoldenrod'><b>GalGame</b></font>, name field data is bound to resource files such as image or voice files"
        "<br>"
        "Translating these name fields can cause errors. In such cases, this feature can be disabled, enabled by default"
        "<br>"
        "Supported formats:"
        "<br>"
        "• RenPy exported game text (.rpy)"
        "<br>"
        "• VNTextPatch or SExtractor exported game text with name fields (.json)"
    )
    expert_settings_page_auto_process_prefix_suffix_preserved_text: str = "Auto Process Prefix/Suffix Preserved Text"
    expert_settings_page_auto_process_prefix_suffix_preserved_text_desc: str = (
        "Whether to auto-process text segments at the start/end that match preserve rules, enabled by default"
        "<br>"
        "• Enabled: Removes segments matching preserve rules and restores them after translation"
        "<br>"
        "• Disabled: Sends the full text for better context, but may reduce preserve effectiveness"
    )

    # 质量类通用
    quality_import: str = "Import"
    quality_import_toast: str = "Data imported …"
    quality_export: str = "Export"
    quality_export_toast: str = "Data exported …"
    quality_merge_duplication: str = "Merged duplicate entries …"
    quality_delete_confirm: str = "Confirm deleting {COUNT} item(s)?"
    quality_query: str = "Query"
    quality_preset: str = "Preset"
    quality_select_file_type: str = "Supported Formats (*.json *.xlsx)"
    quality_delete_row: str = "Delete Row"
    quality_delete_preset: str = "Delete Preset"
    quality_save_preset: str = "Save Preset"
    quality_save_preset_title: str = "Save as Preset"
    quality_save_preset_success: str = "Preset saved …"
    quality_set_as_default_preset: str = "Set as Default Preset"
    quality_cancel_default_preset: str = "Cancel Default Preset"
    quality_set_default_preset_success: str = "Default preset set …"
    quality_cancel_default_preset_success: str = "Default preset cancelled …"
    quality_default_preset_loaded_toast: str = "Default preset loaded: {NAME} …"
    quality_reorder: str = "Reorder"
    quality_statistics_action: str = "Statistics"
    quality_statistics_col_status: str = "Status"
    quality_statistics_tooltip_count: str = "Matched item count: {COUNT}"
    quality_statistics_tooltip_relation_header: str = "Contains relations:"
    quality_statistics_tooltip_relation_line: str = "{CHILD} -> {PARENT}"
    quality_statistics_progress: str = "Counting rules, item {CURRENT} of {TOTAL} …"

    # 规则列
    enable: str = "Enable"
    disable: str = "Disable"
    rule_regex: str = "Regular Expression"
    rule_case_sensitive: str = "Case Sensitive"

    # 术语表
    glossary_page_head_content: str = "By building a glossary in the prompt to guide model translation, unified translation and correction of personal pronouns can be achieved"
    glossary_page_table_row_04: str = "Description"
    glossary_page_kg: str = "One-Click Tools"

    # 文本保护
    text_preserve_page_head_content: str = (
            "Preserve text segments like code snippets, control characters, and style characters that shouldn't be translated, preventing incorrect translation"
            "<br>"
            "• Off - Does not use any protection rules, leaving judgment and processing entirely to the AI"
            "<br>"
            "• Smart - Automatically determines the text format and game engine to select appropriate protection rules"
            "<br>"
            "• Custom - Protects corresponding text matched based on the <font color='darkgoldenrod'><b>Regex Rules</b></font> configured on this page"
        )
    text_preserve_mode_off: str = "Off"
    text_preserve_mode_smart: str = "Smart"
    text_preserve_mode_custom: str = "Custom"
    text_preserve_page_table_row_02: str = "Remarks (For reference only, has no actual effect)"

    # 译前替换
    pre_translation_replacement_page_head_title: str = "Pre-translation Replacement"
    pre_translation_replacement_page_head_content: str = (
        "Before translation, matched parts of the original text will be replaced by specified text, processed in top-down order"
        "<br>"
        "For <font color='darkgoldenrod'><b>RPGMaker MV/MZ</b></font> engine games:"
        "<br>"
        "• Importing <font color='darkgoldenrod'><b>actors.json</b></font> from <font color='darkgoldenrod'><b>data</b></font> or <font color='darkgoldenrod'><b>www\\data</b></font> in the game directory can improve translation quality"
        "<br>"
        "• Special handling is needed for games with custom names. Click the bottom-right button to see <font color='darkgoldenrod'><b>Wiki</b></font> instructions"
    )

    # 译后替换
    post_translation_replacement_page_head_title: str = "Post-translation Replacement"
    post_translation_replacement_page_head_content: str = "After translation is completed, replace the matched parts in the translated text with the specified text, the execution order is from top to bottom"

    # 自定义提示词 - 翻译
    translation_prompt_page_head: str = "Custom Translation Prompts (SakuraLLM model not supported)"
    translation_prompt_page_head_desc: str = (
        "Add extra translation requirements such as story settings and writing styles via custom prompts"
        "<br>"
        "Note: The prefix and suffix are fixed and cannot be modified"
        "<br>"
        "The content on this page is only used in translation tasks after this page is enabled"
    )

    # 自定义提示词 - 分析
    analysis_prompt_page_head: str = "Custom Analysis Prompts"
    analysis_prompt_page_head_desc: str = (
        "Adjust glossary analysis scope and output requirements through custom prompts"
        "<br>"
        "Note: The prefix and suffix are fixed and cannot be modified"
        "<br>"
        "The content on this page is only used in analysis tasks after this page is enabled"
    )

    # 自定义提示词 - 导入导出
    custom_prompt_select_file_type: str = "Supported Files (*.txt)"

    # 实验室
    laboratory_page_mtool_optimizer_enable: str = "MTool Optimizer"
    laboratory_page_mtool_optimizer_enable_desc: str = (
        "Can reduce translation time and token usage by up to 40% when translating MTool text"
        "<br>"
        "May lead to issues like <font color='darkgoldenrod'><b>residual original text</b></font> or <font color='darkgoldenrod'><b>incoherent sentences</b></font>"
        "<br>"
        "It should <font color='darkgoldenrod'><b>only be enabled when translating MTool text</b></font>"
        "<br>"
        "Please <font color='darkgoldenrod'><b>decide for yourself</b></font> whether to enable this feature"
        ""
        ""
    )
    laboratory_page_force_thinking_enable: str = "Force Thinking"
    laboratory_page_force_thinking_enable_desc: str = (
        "When enabled, non-thinking models will also perform thinking before translation, enabled by default, and does not support SakuraLLM"
        "<br>"
        "◈ Trade a slight increase in Token consumption for improved translation quality"
        "<br>"
        "◈ Not recommended for reasoning models, as redundant reasoning provides little benefit"
        "<br>"
        "◈ When functioning normally, model reasoning output will be visible in the translation logs"
    )
    laboratory_page_auto_glossary_enable: str = "Auto Complete Glossary"
    laboratory_page_auto_glossary_enable_desc: str = (
        "Automatically supplement the glossary while translating, disabled by default, and does not support SakuraLLM"
        "<br>"
        "◈ Intended only for filling gaps; it may generate <font color='darkgoldenrod'><b>incorrect or inappropriate</b></font> data"
        "<br>"
        "◈ Recommended to enable this feature on top of a complete, filtered glossary obtained using <font color='darkgoldenrod'><b>KeywordGacha</b></font>"
    )

    # 百宝箱
    tool_box_page_name_field_extraction_desc: str = (
        "Extract character name field data from <font color='darkgoldenrod'><b>RenPy</b></font> and <font color='darkgoldenrod'><b>GalGame</b></font> game text, "
        "and automatically generate corresponding glossary data to facilitate subsequent translation"
    )
    tool_box_page_ts_conversion: str = "TS Conversion"
    tool_box_page_ts_conversion_desc: str = "Batch convert the target text or character names between Traditional and Simplified Chinese with text protection"

    # 百宝箱 - 姓名字段提取
    name_field_extraction_page: str = "Name-Field Extraction"
    name_field_extraction_page_desc: str = (
        "Extract character name fields from all eligible files in the <font color='darkgoldenrod'><b>input folder</b></font> and automatically generate corresponding glossary data"
        "<br>"
        "Please note: This function <font color='darkgoldenrod'><b>cannot extract terms from the main text</b></font>, and cannot replace the <font color='darkgoldenrod'><b>KeywordGacha</b></font> tool"
        "<br>"
        "Supported formats:"
        "<br>"
        "• RenPy exported game text (.rpy)"
        "<br>"
        "• VNTextPatch or SExtractor exported game text with name fields (.json)"
    )
    name_field_extraction_action_extract: str = "Extract"
    name_field_extraction_action_translate: str = "Translate"
    name_field_extraction_action_import: str = "Import To Glossary"
    name_field_extraction_action_progress: str = "Extracting name fields …"
    name_field_extraction_context: str = "Context"

    # 百宝箱 - 繁简转换
    ts_conversion_page: str = "Traditional-Simplified Conversion"
    ts_conversion_page_desc: str = "Convert translated text in the project between Simplified Chinese and Traditional Chinese"
    ts_conversion_direction: str = "Conversion Mode"
    ts_conversion_direction_desc: str = "Conversion is implemented by OpenCC, Simplified to Traditional uses S2TW rules, Traditional to Simplified uses T2S rules"
    ts_conversion_to_traditional: str = "Simplified to Traditional"
    ts_conversion_to_simplified: str = "Traditional to Simplified"
    ts_conversion_target_name: str = "Convert Name Field Translations"
    ts_conversion_target_name_desc: str = (
        "In some <font color='darkgoldenrod'><b>GalGame</b></font>, name field data is bound to resource files such as image or voice files"
        "<br>"
        "Translating these name fields can cause errors. In such cases, this feature can be disabled, enabled by default"
    )
    ts_conversion_preserve_text: str = "Follow Text Protection Rules"
    ts_conversion_preserve_text_desc: str = "Follow text protection rules to avoid damaging code segments in the game text during the conversion process"
    ts_conversion_action_start: str = "Start Conversion"
    ts_conversion_action_confirm: str = "Start Traditional-Simplified conversion …?"
    ts_conversion_action_progress: str = "Converting Traditional-Simplified, item {CURRENT} of {TOTAL} …"
    ts_conversion_action_preparing: str = "Preparing conversion data …"
